#!/usr/bin/env node

/**
 * fatten-snake.js
 *
 * Post-processes the SVGs generated by Platane/snk to add a progressive
 * stroke-width animation — the snake visually fattens as it eats cells.
 *
 * Configuration (via environment variables):
 *   SNAKE_MIN_WIDTH  — starting stroke width in px  (default: 1.5)
 *   SNAKE_MAX_WIDTH  — ending stroke width in px     (default: 10)
 *   SNAKE_EASING     — CSS animation timing function (default: ease-in)
 */

"use strict";

const fs = require("fs");
const path = require("path");

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const CONFIG = {
  distDir: path.resolve("dist"),
  minWidth: parseFloat(process.env.SNAKE_MIN_WIDTH ?? "1.5"),
  maxWidth: parseFloat(process.env.SNAKE_MAX_WIDTH ?? "10"),
  easing: process.env.SNAKE_EASING ?? "ease-in",
  /** Element types and class fragments snk may use for the snake body. */
  snakeSelectors: [
    { tag: "path", classFragment: "snake" },
    { tag: "polyline", classFragment: "snake" },
    { tag: "rect", classFragment: "snake" },
  ],
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Extracts the primary animation duration (in seconds) from an SVG string.
 * Falls back to a sensible default if none is found.
 *
 * @param {string} svg
 * @returns {string} Duration string, e.g. "3.5"
 */
function extractDuration(svg) {
  const match = svg.match(/animation(?:-duration)?[^:]*:\s*[\w\s,]*?([\d.]+)s/);
  return match ? match[1] : "3.5";
}

/**
 * Builds the @keyframes block for the progressive fatten animation.
 *
 * @param {number} minWidth
 * @param {number} maxWidth
 * @returns {string}
 */
function buildKeyframes(minWidth, maxWidth) {
  return `
  @keyframes snakeFatten {
    0%   { stroke-width: ${minWidth}px; }
    40%  { stroke-width: ${(minWidth + maxWidth * 0.3).toFixed(1)}px; }
    80%  { stroke-width: ${(maxWidth * 0.75).toFixed(1)}px; }
    100% { stroke-width: ${maxWidth}px; }
  }`;
}

/**
 * Injects the fatten keyframes into the SVG's <style> block.
 * Skips injection if already present (idempotent).
 *
 * @param {string} svg
 * @param {number} minWidth
 * @param {number} maxWidth
 * @returns {string}
 */
function injectKeyframes(svg, minWidth, maxWidth) {
  if (svg.includes("snakeFatten")) return svg;

  const keyframes = buildKeyframes(minWidth, maxWidth);

  if (svg.includes("</style>")) {
    return svg.replace("</style>", `${keyframes}\n  </style>`);
  }

  // No <style> block — inject one before </svg>
  return svg.replace(
    "</svg>",
    `<style>${keyframes}\n  </style>\n</svg>`
  );
}

/**
 * Attaches the snakeFatten animation to every snake element in the SVG.
 * Skips elements that are already patched (idempotent).
 *
 * @param {string} svg
 * @param {string} duration  Animation duration in seconds
 * @param {string} easing    CSS timing function
 * @param {Array}  selectors Element/class selectors to target
 * @returns {{ svg: string, patchedCount: number }}
 */
function attachAnimation(svg, duration, easing, selectors) {
  let patchedCount = 0;

  for (const { tag, classFragment } of selectors) {
    const pattern = new RegExp(
      `(<${tag}[^>]*class="[^"]*${classFragment}[^"]*"[^>]*?)(\\/?>)`,
      "g"
    );

    svg = svg.replace(pattern, (match, el, close) => {
      if (el.includes("snakeFatten")) return match;

      patchedCount++;
      const animationDecl = `animation: snakeFatten ${duration}s ${easing} infinite;`;

      // Merge into an existing style attribute, or add a new one
      if (el.includes('style="')) {
        return el.replace('style="', `style="${animationDecl} `) + close;
      }
      return `${el} style="${animationDecl}"${close}`;
    });
  }

  return { svg, patchedCount };
}

/**
 * Processes a single SVG file in-place.
 *
 * @param {string} filepath  Absolute path to the SVG file
 * @returns {{ patchedCount: number, duration: string }}
 */
function processSvg(filepath) {
  let svg = fs.readFileSync(filepath, "utf8");

  const duration = extractDuration(svg);
  svg = injectKeyframes(svg, CONFIG.minWidth, CONFIG.maxWidth);

  const { svg: patchedSvg, patchedCount } = attachAnimation(
    svg,
    duration,
    CONFIG.easing,
    CONFIG.snakeSelectors
  );

  fs.writeFileSync(filepath, patchedSvg, "utf8");
  return { patchedCount, duration };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  console.log("🐍  fatten-snake — applying progressive width animation\n");
  console.log(
    `  Config: width ${CONFIG.minWidth}px → ${CONFIG.maxWidth}px, easing: ${CONFIG.easing}\n`
  );

  if (!fs.existsSync(CONFIG.distDir)) {
    console.error(`  ✖  dist directory not found at: ${CONFIG.distDir}`);
    console.error("     Ensure Platane/snk ran successfully before this step.");
    process.exit(1);
  }

  const svgFiles = fs
    .readdirSync(CONFIG.distDir)
    .filter((f) => f.endsWith(".svg"))
    .map((f) => path.join(CONFIG.distDir, f));

  if (svgFiles.length === 0) {
    console.error("  ✖  No SVG files found in dist/. Nothing to process.");
    process.exit(1);
  }

  let totalPatched = 0;

  for (const filepath of svgFiles) {
    const filename = path.basename(filepath);
    try {
      const { patchedCount, duration } = processSvg(filepath);
      totalPatched += patchedCount;

      if (patchedCount > 0) {
        console.log(
          `  ✔  ${filename}  (${patchedCount} element(s) patched, duration: ${duration}s)`
        );
      } else {
        console.warn(
          `  ⚠  ${filename}  — no snake elements matched. ` +
            `SVG structure may differ from expected; inspect manually.`
        );
      }
    } catch (err) {
      console.error(`  ✖  ${filename}  — ${err.message}`);
      process.exit(1);
    }
  }

  console.log(
    `\n  Done. ${totalPatched} total element(s) patched across ${svgFiles.length} file(s).`
  );
}

main();
